import { Property, PropertyAmenity, UserProfile, Lead, Conversation } from '../types';

export const AMENITIES_LIST: PropertyAmenity[] = [
  { id: 'piscina', name: 'Piscina Adulto e Infantil', category: 'lazer', icon: 'Waves' },
  { id: 'churrasqueira', name: 'Churrasqueira Gourmet', category: 'lazer', icon: 'Flame' },
  { id: 'academia', name: 'Academia Completa', category: 'lazer', icon: 'Dumbbell' },
  { id: 'quadra_tenis', name: 'Quadra de Tênis / Beach Tennis', category: 'lazer', icon: 'Trophy' },
  { id: 'playground', name: 'Playground', category: 'lazer', icon: 'Smile' },
  { id: 'salao_festas', name: 'Salão de Festas', category: 'lazer', icon: 'PartyPopper' },
  { id: 'espaco_gourmet', name: 'Espaço Gourmet', category: 'lazer', icon: 'Utensils' },
  { id: 'cinema', name: 'Cinema / Coworking', category: 'lazer', icon: 'Film' },
  { id: 'sauna', name: 'Sauna & Spa', category: 'conforto', icon: 'Sparkles' },
  { id: 'portaria_24h', name: 'Portaria & Segurança 24h', category: 'seguranca', icon: 'ShieldCheck' },
  { id: 'cameras_seguranca', name: 'Monitoramento por Câmeras', category: 'seguranca', icon: 'Camera' },
  { id: 'alarme', name: 'Alarme Individual', category: 'seguranca', icon: 'Bell' },
  { id: 'elevador', name: 'Elevador Privativo / Social', category: 'estrutura', icon: 'ArrowUpDown' },
  { id: 'ar_condicionado', name: 'Ar-Condicionado Instalado', category: 'conforto', icon: 'Wind' },
  { id: 'varanda_gourmet', name: 'Varanda Gourmet Integrada', category: 'conforto', icon: 'Wine' },
  { id: 'energia_solar', name: 'Energia Solar Fotovoltaica', category: 'estrutura', icon: 'Sun' },
  { id: 'carregador_eletrico', name: 'Ponto p/ Carro Elétrico', category: 'estrutura', icon: 'Zap' },
  { id: 'pet_place', name: 'Pet Place / Pet Care', category: 'conforto', icon: 'Dog' },
  { id: 'moveis_planejados', name: 'Móveis Planejados', category: 'conforto', icon: 'Armchair' },
  { id: 'aquecimento_gas', name: 'Aquecimento a Gás', category: 'conforto', icon: 'Thermometer' },
];

export const BROKERS: UserProfile[] = [
  {
    id: 'user_1',
    name: 'Carlos Mendes Ortega',
    email: 'carlos.mendes@imovelhub.com.br',
    phone: '(15) 3232-9092',
    whatsapp: '5515998765432',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&q=80',
    role: 'broker',
    creci: '9835-J',
    agencyName: 'Mendes Ortega Imóveis',
    agencyLogo: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=128&q=80',
    verified: true,
    activeListingsCount: 24,
    rating: 4.9,
    totalDeals: 142
  },
  {
    id: 'user_2',
    name: 'Helena Albuquerque',
    email: 'helena.albuquerque@imovelhub.com.br',
    phone: '(11) 3456-7890',
    whatsapp: '5511987651234',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
    role: 'broker',
    creci: '142850-F',
    agencyName: 'Albuquerque Private Homes',
    verified: true,
    activeListingsCount: 18,
    rating: 5.0,
    totalDeals: 89
  },
  {
    id: 'user_current',
    name: 'Edson Ricardo',
    email: 'edsonricardosouza@gmail.com',
    phone: '(15) 99123-4567',
    whatsapp: '5515991234567',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
    role: 'broker',
    creci: '185420-F',
    agencyName: 'Ricardo & Souza Consultoria Imobiliária',
    agencyLogo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=128&q=80',
    verified: true,
    activeListingsCount: 8,
    rating: 4.8,
    totalDeals: 36
  }
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    code: '24636068-MEOA',
    userId: 'user_current',
    advertiser: BROKERS[2],
    title: 'Central Station - Apartamento Alto Padrão no Centro',
    slug: 'central-station-apartamento-sorocaba-centro-24636068',
    description: 'No coração vibrante de Sorocaba, nasce um novo ícone urbano: Central Station. Um empreendimento que une mobilidade, conveniência e valorização em um só endereço. Apartamento finamente decorado com acabamentos nobres, varanda gourmet integrada à sala e cozinha americana.',
    purpose: 'sale',
    type: 'apartment',
    status: 'active',
    featured: true,
    isExclusive: true,
    price: 485000,
    pricePerMeter: 9700,
    condoFee: 420,
    iptuFee: 110,
    totalArea: 68,
    usefulArea: 50,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 1,
    floor: 12,
    totalFloors: 24,
    solarOrientation: 'Manhã',
    constructionYear: 2024,
    addressStreet: 'Rua da Penha',
    addressNumber: '1320',
    neighborhood: 'Centro',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18010-002',
    latitude: -23.5015,
    longitude: -47.4580,
    amenities: ['piscina', 'academia', 'varanda_gourmet', 'portaria_24h', 'elevador', 'ar_condicionado', 'aquecimento_gas'],
    media: [
      {
        id: 'm1',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Living integrado com iluminação em LED',
        category: 'sala',
        isCover: true,
        order: 1
      },
      {
        id: 'm2',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Sala de jantar e bancada contemporânea',
        category: 'sala',
        isCover: false,
        order: 2
      },
      {
        id: 'm3',
        url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Suíte master com cabeceira ripada e painéis em marcenaria',
        category: 'quarto',
        isCover: false,
        order: 3
      },
      {
        id: 'm4',
        url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Banheiro com bancada em mármore esculpido',
        category: 'banheiro',
        isCover: false,
        order: 4
      }
    ],
    viewsCount: 3840,
    leadsCount: 42,
    favoritesCount: 156,
    sharesCount: 28,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-30T14:20:00Z'
  },
  {
    id: 'prop-2',
    code: '38914022-ALPH',
    userId: 'user_current',
    advertiser: BROKERS[2],
    title: 'Mansão Neoclássica com Vista Panorâmica em Alphaville',
    slug: 'mansao-neoclassica-alphaville-nova-esplanada-38914022',
    description: 'Espetacular residência em condomínio fechado com arquitetura contemporânea e acabamentos importados. Pé direito duplo de 7 metros, automação residencial completa, adega climatizada, elevador privativo e piscina com borda infinita aquecida.',
    purpose: 'sale',
    type: 'condo_house',
    status: 'active',
    featured: true,
    isExclusive: true,
    price: 3750000,
    pricePerMeter: 8333,
    condoFee: 1100,
    iptuFee: 480,
    totalArea: 650,
    usefulArea: 450,
    bedrooms: 4,
    suites: 4,
    bathrooms: 6,
    parkingSpots: 6,
    floor: 2,
    totalFloors: 2,
    solarOrientation: 'Norte',
    constructionYear: 2025,
    addressStreet: 'Alameda dos Ipês',
    neighborhood: 'Alphaville Nova Esplanada',
    city: 'Votorantim',
    state: 'SP',
    zipCode: '18118-000',
    latitude: -23.5510,
    longitude: -47.4720,
    amenities: ['piscina', 'churrasqueira', 'academia', 'quadra_tenis', 'sauna', 'portaria_24h', 'varanda_gourmet', 'energia_solar', 'carregador_eletrico'],
    media: [
      {
        id: 'm201',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Fachada imponente com iluminação cênica noturna',
        category: 'fachada',
        isCover: true,
        order: 1
      },
      {
        id: 'm202',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Área de lazer com piscina de borda infinita e deck de madeira',
        category: 'lazer',
        isCover: false,
        order: 2
      },
      {
        id: 'm203',
        url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Living com pé direito duplo e lareira a gás',
        category: 'sala',
        isCover: false,
        order: 3
      }
    ],
    viewsCount: 5120,
    leadsCount: 31,
    favoritesCount: 284,
    sharesCount: 65,
    createdAt: '2026-08-01T12:00:00Z',
    updatedAt: '2026-08-28T09:15:00Z'
  },
  {
    id: 'prop-3',
    code: '19854091-CAMP',
    userId: 'user_1',
    advertiser: BROKERS[0],
    title: 'Apartamento Garden no Parque Campolim com 3 Suítes',
    slug: 'apartamento-garden-parque-campolim-sorocaba-19854091',
    description: 'Privilégio de morar em uma casa com a segurança de um condomínio vertical. Área externa privativa de 65m² com jacuzzi aquecida e espaço gourmet exclusivo.',
    purpose: 'sale',
    type: 'apartment',
    status: 'active',
    featured: true,
    price: 1350000,
    pricePerMeter: 8437,
    condoFee: 890,
    iptuFee: 240,
    totalArea: 210,
    usefulArea: 160,
    bedrooms: 3,
    suites: 3,
    bathrooms: 4,
    parkingSpots: 3,
    floor: 1,
    totalFloors: 18,
    solarOrientation: 'Manhã',
    constructionYear: 2023,
    addressStreet: 'Avenida Professora Izoraida Marques Peres',
    neighborhood: 'Parque Campolim',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18048-110',
    latitude: -23.5280,
    longitude: -47.4650,
    amenities: ['piscina', 'churrasqueira', 'academia', 'playground', 'salao_festas', 'portaria_24h', 'pet_place', 'moveis_planejados'],
    media: [
      {
        id: 'm301',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Garden privativo com pergolado e spa',
        category: 'lazer',
        isCover: true,
        order: 1
      },
      {
        id: 'm302',
        url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Cozinha planejada com ilha central e eletros embutidos',
        category: 'cozinha',
        isCover: false,
        order: 2
      }
    ],
    viewsCount: 2790,
    leadsCount: 19,
    favoritesCount: 98,
    sharesCount: 14,
    createdAt: '2026-08-15T15:30:00Z',
    updatedAt: '2026-08-29T18:00:00Z'
  },
  {
    id: 'prop-4',
    code: '74125896-ALUG',
    userId: 'user_1',
    advertiser: BROKERS[0],
    title: 'Casa Térrea Mobiliada para Locação no Condomínio Giverny',
    slug: 'casa-terrea-condominio-giverny-locacao-74125896',
    description: 'Casa totalmente térrea, mobiliada e decorada com projeto assinado por arquiteto renomado. 3 suítes completas, piscina aquecida com hidro, energia solar e ar-condicionado em todos os cômodos.',
    purpose: 'rent',
    type: 'condo_house',
    status: 'active',
    featured: false,
    price: 14000,
    condoFee: 750,
    iptuFee: 320,
    totalArea: 380,
    usefulArea: 240,
    bedrooms: 3,
    suites: 3,
    bathrooms: 4,
    parkingSpots: 4,
    solarOrientation: 'Tarde',
    constructionYear: 2022,
    addressStreet: 'Rua Claude Monet',
    neighborhood: 'Giverny',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18048-000',
    latitude: -23.5410,
    longitude: -47.4690,
    amenities: ['piscina', 'churrasqueira', 'quadra_tenis', 'portaria_24h', 'ar_condicionado', 'energia_solar', 'moveis_planejados'],
    media: [
      {
        id: 'm401',
        url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Fachada frontal moderna com paisagismo tropical',
        category: 'fachada',
        isCover: true,
        order: 1
      },
      {
        id: 'm402',
        url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Suíte master com closet e vista para o jardim privativo',
        category: 'quarto',
        isCover: false,
        order: 2
      }
    ],
    viewsCount: 1650,
    leadsCount: 14,
    favoritesCount: 72,
    sharesCount: 11,
    createdAt: '2026-08-18T08:00:00Z',
    updatedAt: '2026-08-30T11:00:00Z'
  },
  {
    id: 'prop-5',
    code: '9595997-MEOA',
    userId: 'user_2',
    advertiser: BROKERS[1],
    title: 'Arbo Paulistano - Apartamentos de 80 a 115m² em Construção',
    slug: 'arbo-paulistano-apartamentos-sorocaba-9595997',
    description: 'Breve lançamento no ponto mais nobre da Zona Sul. Torre única com lazer estilo resort, piscina climatizada com raia de 25m, pista de caminhada privativa, coworking e bicicletário compartilhado.',
    purpose: 'launch',
    type: 'apartment',
    status: 'active',
    featured: true,
    price: 790000,
    pricePerMeter: 9875,
    condoFee: 550,
    iptuFee: 180,
    totalArea: 115,
    usefulArea: 80,
    bedrooms: 3,
    suites: 2,
    bathrooms: 3,
    parkingSpots: 2,
    deliveryDate: '2027-12-01',
    addressStreet: 'Rua Senador Vergueiro',
    neighborhood: 'Jardim Paulistano',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18040-000',
    latitude: -23.5150,
    longitude: -47.4520,
    amenities: ['piscina', 'churrasqueira', 'academia', 'cinema', 'sauna', 'portaria_24h', 'carregador_eletrico', 'pet_place'],
    media: [
      {
        id: 'm501',
        url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Perspectiva artística da fachada do Arbo Paulistano',
        category: 'fachada',
        isCover: true,
        order: 1
      },
      {
        id: 'm502',
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Complexo aquático com bangalôs e deck molhado',
        category: 'lazer',
        isCover: false,
        order: 2
      }
    ],
    viewsCount: 6200,
    leadsCount: 88,
    favoritesCount: 310,
    sharesCount: 94,
    createdAt: '2026-07-25T11:00:00Z',
    updatedAt: '2026-08-30T17:45:00Z'
  },
  {
    id: 'prop-6',
    code: '45812390-ALUG',
    userId: 'user_current',
    advertiser: BROKERS[2],
    title: 'Studio Mobiliado & Equipado no Além Ponte - Ideal p/ Investidores',
    slug: 'studio-mobiliado-alem-ponte-sorocaba-45812390',
    description: 'Studio pronto para morar ou rentabilizar em Airbnb com retorno estimado de 0.8% ao mês. Mobília planejada completa, eletrodomésticos inverter, fechadura digital biométrica e vaga de garagem coberta.',
    purpose: 'rent',
    type: 'apartment',
    status: 'active',
    featured: false,
    price: 2400,
    condoFee: 320,
    iptuFee: 65,
    totalArea: 42,
    usefulArea: 36,
    bedrooms: 1,
    suites: 1,
    bathrooms: 1,
    parkingSpots: 1,
    floor: 7,
    totalFloors: 14,
    solarOrientation: 'Manhã',
    constructionYear: 2024,
    addressStreet: 'Rua Coronel Nogueira Padilha',
    neighborhood: 'Além Ponte',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18020-000',
    latitude: -23.5080,
    longitude: -47.4430,
    amenities: ['academia', 'cinema', 'portaria_24h', 'elevador', 'ar_condicionado', 'moveis_planejados'],
    media: [
      {
        id: 'm601',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Studio com divisória ripada entre quarto e estar',
        category: 'sala',
        isCover: true,
        order: 1
      }
    ],
    viewsCount: 1420,
    leadsCount: 18,
    favoritesCount: 65,
    sharesCount: 9,
    createdAt: '2026-08-20T14:00:00Z',
    updatedAt: '2026-08-30T16:00:00Z'
  },
  {
    id: 'prop-7',
    code: '88210344-IBITI',
    userId: 'user_2',
    advertiser: BROKERS[1],
    title: 'Casa Térrea Moderna com Piscina no Condomínio Ibiti Reserva',
    slug: 'casa-terrea-ibiti-reserva-sorocaba-88210344',
    description: 'Projeto moderno e clean no cobiçado Ibiti Reserva. 3 suítes sendo 1 master com hidromassagem e closet espaçoso. Cozinha integrada à área gourmet e piscina com cascata.',
    purpose: 'sale',
    type: 'condo_house',
    status: 'active',
    featured: false,
    price: 1180000,
    pricePerMeter: 5900,
    condoFee: 410,
    iptuFee: 160,
    totalArea: 300,
    usefulArea: 200,
    bedrooms: 3,
    suites: 3,
    bathrooms: 4,
    parkingSpots: 4,
    solarOrientation: 'Manhã',
    constructionYear: 2024,
    addressStreet: 'Alameda dos Jacarandás',
    neighborhood: 'Ibiti Reserva',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18087-000',
    latitude: -23.4680,
    longitude: -47.4320,
    amenities: ['piscina', 'churrasqueira', 'quadra_tenis', 'playground', 'portaria_24h', 'energia_solar'],
    media: [
      {
        id: 'm701',
        url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Fachada moderna em tons de concreto e madeira ripada',
        category: 'fachada',
        isCover: true,
        order: 1
      }
    ],
    viewsCount: 2310,
    leadsCount: 22,
    favoritesCount: 88,
    sharesCount: 19,
    createdAt: '2026-08-12T16:00:00Z',
    updatedAt: '2026-08-29T10:30:00Z'
  },
  {
    id: 'prop-8',
    code: '33491022-SANTA',
    userId: 'user_current',
    advertiser: BROKERS[2],
    title: 'Apartamento com Varanda Gourmet no Jardim Santa Rosália',
    slug: 'apartamento-jardim-santa-rosalia-sorocaba-33491022',
    description: 'Excelente localização próximo às principais avenidas e hipermercados. 3 dormitórios, varanda com churrasqueira a carvão e 2 vagas cobertas demarcadas.',
    purpose: 'sale',
    type: 'apartment',
    status: 'paused',
    featured: false,
    price: 620000,
    pricePerMeter: 6888,
    condoFee: 490,
    iptuFee: 130,
    totalArea: 110,
    usefulArea: 90,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 2,
    floor: 6,
    totalFloors: 16,
    solarOrientation: 'Manhã',
    constructionYear: 2021,
    addressStreet: 'Rua Nicolau Pereira Campos Vergueiro',
    neighborhood: 'Jardim Santa Rosália',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18095-000',
    latitude: -23.4920,
    longitude: -47.4470,
    amenities: ['piscina', 'churrasqueira', 'academia', 'salao_festas', 'portaria_24h', 'elevador'],
    media: [
      {
        id: 'm801',
        url: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Varanda gourmet com fechamento em vidro retrátil',
        category: 'sala',
        isCover: true,
        order: 1
      }
    ],
    viewsCount: 890,
    leadsCount: 6,
    favoritesCount: 34,
    sharesCount: 4,
    createdAt: '2026-08-05T10:00:00Z',
    updatedAt: '2026-08-25T12:00:00Z'
  }
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    propertyId: 'prop-1',
    propertyTitle: 'Central Station - Apartamento Alto Padrão no Centro',
    propertyCode: '24636068-MEOA',
    propertyPrice: 485000,
    propertyImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=400&q=80',
    advertiserId: 'user_current',
    buyerName: 'Mariana Silveira',
    buyerEmail: 'mariana.silveira@gmail.com',
    buyerPhone: '(15) 99788-1234',
    message: 'Olá! Tenho interesse no imóvel código 24636068-MEOA. Gostaria de agendar uma visita presencial neste sábado pela manhã e saber sobre as opções de financiamento.',
    origin: 'portal_form',
    status: 'visit_scheduled',
    notes: 'Cliente pré-aprovada na Caixa Econômica. Visita agendada para sábado às 10h30.',
    budget: 500000,
    scheduledVisitDate: '2026-09-05T10:30:00',
    createdAt: '2026-08-30T14:15:00Z',
    updatedAt: '2026-08-30T16:00:00Z'
  },
  {
    id: 'lead-2',
    propertyId: 'prop-2',
    propertyTitle: 'Mansão Neoclássica com Vista Panorâmica em Alphaville',
    propertyCode: '38914022-ALPH',
    propertyPrice: 3750000,
    propertyImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=400&q=80',
    advertiserId: 'user_current',
    buyerName: 'Dr. Roberto Vasconcelos',
    buyerEmail: 'roberto.vasconcelos@med.br',
    buyerPhone: '(11) 98122-9988',
    message: 'Gostaria de saber se o proprietário aceita permuta parcial por apartamento no Campolim no valor de R$ 1.2M.',
    origin: 'whatsapp_click',
    status: 'proposal_made',
    notes: 'Enviada contraproposta. Aguardando retorno da análise da documentação do apartamento de permuta.',
    budget: 3800000,
    createdAt: '2026-08-29T11:00:00Z',
    updatedAt: '2026-08-30T09:30:00Z'
  },
  {
    id: 'lead-3',
    propertyId: 'prop-6',
    propertyTitle: 'Studio Mobiliado & Equipado no Além Ponte',
    propertyCode: '45812390-ALUG',
    propertyPrice: 2400,
    propertyImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=400&q=80',
    advertiserId: 'user_current',
    buyerName: 'Lucas Fernandes',
    buyerEmail: 'lucas.fernandes@tech.io',
    buyerPhone: '(15) 98877-6655',
    message: 'Preciso me mudar urgente no dia 15 deste mês por conta de transferência de trabalho. Qual a garantia locatícia solicitada?',
    origin: 'portal_form',
    status: 'new',
    notes: 'Aceita seguro fiança CredPago ou fiador.',
    budget: 2500,
    createdAt: '2026-08-31T04:20:00Z',
    updatedAt: '2026-08-31T04:20:00Z'
  },
  {
    id: 'lead-4',
    propertyId: 'prop-1',
    propertyTitle: 'Central Station - Apartamento Alto Padrão no Centro',
    propertyCode: '24636068-MEOA',
    propertyPrice: 485000,
    propertyImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=400&q=80',
    advertiserId: 'user_current',
    buyerName: 'Camila Duarte',
    buyerEmail: 'camiladuarte@adv.br',
    buyerPhone: '(15) 99111-2233',
    message: 'Tem vaga para carro grande tipo SUV? Aceita proposta à vista com desconto?',
    origin: 'phone_call',
    status: 'contacted',
    notes: 'Vaga é coberta no subsolo 1, cabe SUV tranquilamente.',
    budget: 460000,
    createdAt: '2026-08-28T09:40:00Z',
    updatedAt: '2026-08-28T14:00:00Z'
  }
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    propertyId: 'prop-1',
    propertyTitle: 'Central Station - Apartamento no Centro',
    propertyImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=400&q=80',
    propertyPrice: 485000,
    otherUser: {
      id: 'buyer-1',
      name: 'Mariana Silveira',
      email: 'mariana.silveira@gmail.com',
      phone: '(15) 99788-1234',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
      role: 'buyer'
    },
    lastMessage: 'Perfeito! Estarei lá no sábado às 10h30. Obrigada pelo atendimento rápido!',
    lastMessageTime: '10:45',
    unreadCount: 1,
    messages: [
      {
        id: 'msg-1',
        conversationId: 'conv-1',
        senderId: 'buyer-1',
        senderName: 'Mariana Silveira',
        text: 'Olá Edson, vi seu anúncio do Central Station e adorei as fotos da sala integrada.',
        createdAt: '2026-08-30T14:15:00Z',
        read: true
      },
      {
        id: 'msg-2',
        conversationId: 'conv-1',
        senderId: 'user_current',
        senderName: 'Edson Ricardo',
        text: 'Olá Mariana! Seja bem-vinda. O imóvel é realmente espetacular, com sol da manhã e marcenaria completa. Gostaria de conhecer pessoalmente?',
        createdAt: '2026-08-30T14:20:00Z',
        read: true
      },
      {
        id: 'msg-3',
        conversationId: 'conv-1',
        senderId: 'buyer-1',
        senderName: 'Mariana Silveira',
        text: 'Perfeito! Estarei lá no sábado às 10h30. Obrigada pelo atendimento rápido!',
        createdAt: '2026-08-30T14:35:00Z',
        read: false
      }
    ]
  },
  {
    id: 'conv-2',
    propertyId: 'prop-2',
    propertyTitle: 'Mansão Neoclássica em Alphaville',
    propertyImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=400&q=80',
    propertyPrice: 3750000,
    otherUser: {
      id: 'buyer-2',
      name: 'Dr. Roberto Vasconcelos',
      email: 'roberto.vasconcelos@med.br',
      phone: '(11) 98122-9988',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
      role: 'buyer'
    },
    lastMessage: 'Vou enviar a matrícula do imóvel de permuta para sua análise ainda hoje.',
    lastMessageTime: 'Ontem',
    unreadCount: 0,
    messages: [
      {
        id: 'msg-4',
        conversationId: 'conv-2',
        senderId: 'buyer-2',
        senderName: 'Dr. Roberto Vasconcelos',
        text: 'Boa tarde Edson. O proprietário avalia aceitar imóvel como parte de pagamento?',
        createdAt: '2026-08-29T11:00:00Z',
        read: true
      },
      {
        id: 'msg-5',
        conversationId: 'conv-2',
        senderId: 'user_current',
        senderName: 'Edson Ricardo',
        text: 'Boa tarde Dr. Roberto! Sim, até 35% do valor total se for no Campolim ou Jardim Paulistano com liquidez.',
        createdAt: '2026-08-29T11:30:00Z',
        read: true
      },
      {
        id: 'msg-6',
        conversationId: 'conv-2',
        senderId: 'buyer-2',
        senderName: 'Dr. Roberto Vasconcelos',
        text: 'Vou enviar a matrícula do imóvel de permuta para sua análise ainda hoje.',
        createdAt: '2026-08-29T15:20:00Z',
        read: true
      }
    ]
  }
];

export const POPULAR_CITIES = [
  'Sorocaba',
  'Votorantim',
  'São Paulo',
  'Campinas',
  'Itu',
  'Salto de Pirapora',
  'Araçoiaba da Serra',
  'Porto Feliz',
  'Indaiatuba',
  'Barueri / Alphaville'
];

export const POPULAR_NEIGHBORHOODS = [
  'Parque Campolim',
  'Centro',
  'Jardim Santa Rosália',
  'Jardim Paulistano',
  'Além Ponte',
  'Alphaville Nova Esplanada',
  'Ibiti Reserva',
  'Condomínio Giverny',
  'Granja Olga',
  'Mont Blanc'
];
