import React, { useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, Building2, GripVertical, Loader2, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { useApp, useCatalog } from '../../context/AppContext';
import { createPropertyType, deletePropertyType, PropertyTypeCatalogItem, PropertyTypeInput, setPropertyTypeActive, updatePropertyType } from '../../lib/propertyTypesCatalog';
import { CATALOG_ICON_OPTIONS } from '../../lib/iconOptions';
import { AdminCatalogSection } from './AdminCatalogSection';
import { Switch } from '../ui/Switch';

const emptyForm: PropertyTypeInput = { name:'', description:'', icon:'Building2', displayOrder:10 };
export const AdminPropertyTypesPanel: React.FC<{open:boolean;onToggle:()=>void}> = ({open,onToggle}) => {
  const { addToast } = useApp();
  const { propertyTypes, loadingPropertyTypes, propertyTypesError, refreshPropertyTypes } = useCatalog();
  const [search,setSearch]=useState(''); const [editing,setEditing]=useState<PropertyTypeCatalogItem|null>(null);
  const [form,setForm]=useState<PropertyTypeInput>(emptyForm); const [modalOpen,setModalOpen]=useState(false);
  const [busy,setBusy]=useState<string|null>(null); const [deleteId,setDeleteId]=useState<string|null>(null); const [dragId,setDragId]=useState<string|null>(null);
  const filtered=useMemo(()=>propertyTypes.filter(item=>item.name.toLocaleLowerCase('pt-BR').includes(search.trim().toLocaleLowerCase('pt-BR'))),[propertyTypes,search]);
  const startNew=()=>{setEditing(null);setForm({...emptyForm,displayOrder:propertyTypes.reduce((n,i)=>Math.max(n,i.displayOrder),0)+10});setModalOpen(true);};
  const startEdit=(item:PropertyTypeCatalogItem)=>{setEditing(item);setForm({name:item.name,description:item.description,icon:item.icon,displayOrder:item.displayOrder});setModalOpen(true);};
  const save=async()=>{if(!form.name.trim())return addToast({type:'warning',title:'Nome obrigatório',message:'Informe o nome do tipo de imóvel.'});setBusy(editing?.id||'new');try{if(editing)await updatePropertyType(editing.id,form);else await createPropertyType(form);await refreshPropertyTypes();setModalOpen(false);addToast({type:'success',title:editing?'Tipo atualizado':'Tipo criado',message:'A alteração já está disponível no portal.'});}catch(error:any){addToast({type:'error',title:'Alteração não salva',message:error?.message||'Tente novamente.'});}finally{setBusy(null);}};
  const toggle=async(item:PropertyTypeCatalogItem)=>{setBusy(item.id);try{await setPropertyTypeActive(item.id,!item.isActive);await refreshPropertyTypes();}catch{addToast({type:'error',title:'Situação não alterada'});}finally{setBusy(null);}};
  const remove=async(item:PropertyTypeCatalogItem)=>{setBusy(item.id);try{await deletePropertyType(item.id);await refreshPropertyTypes();addToast({type:'success',title:'Tipo excluído'});}catch(error:any){addToast({type:'warning',title:'Exclusão não realizada',message:error?.message||'Desative o tipo para preservá-lo.'});}finally{setBusy(null);setDeleteId(null);}};
  const swap=async(a:PropertyTypeCatalogItem,b:PropertyTypeCatalogItem)=>{setBusy(a.id);try{await updatePropertyType(a.id,{name:a.name,description:a.description,icon:a.icon,displayOrder:b.displayOrder});await updatePropertyType(b.id,{name:b.name,description:b.description,icon:b.icon,displayOrder:a.displayOrder});await refreshPropertyTypes();}finally{setBusy(null);}};
  const move=async(item:PropertyTypeCatalogItem,direction:-1|1)=>{const ordered=[...propertyTypes].sort((a,b)=>a.displayOrder-b.displayOrder);const index=ordered.findIndex(i=>i.id===item.id);const other=ordered[index+direction];if(other)await swap(item,other);};
  const drop=async(target:PropertyTypeCatalogItem)=>{const source=propertyTypes.find(i=>i.id===dragId);setDragId(null);if(source&&source.id!==target.id)await swap(source,target);};
  const action=<button onClick={startNew} className="px-4 py-2.5 rounded-xl bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold flex items-center justify-center gap-2 shadow-md shadow-rose-600/20"><Plus className="w-4 h-4"/>Novo tipo</button>;
  return <><AdminCatalogSection title="Tipos de imóveis" description="Controle as opções do cadastro, busca e navegação." activeCount={propertyTypes.filter(i=>i.isActive).length} inactiveCount={propertyTypes.filter(i=>!i.isActive).length} open={open} onToggle={onToggle} action={action}>
    {propertyTypesError&&<div className="m-4 p-4 rounded-2xl bg-amber-50 text-amber-800 text-xs flex justify-between gap-3"><span>{propertyTypesError}</span><button onClick={()=>void refreshPropertyTypes()} className="font-bold">Tentar novamente</button></div>}
    <div className="p-4 border-b border-slate-100 dark:border-slate-800"><label className="relative block"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar tipo de imóvel" className="w-full pl-10 pr-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs"/></label></div>
    {loadingPropertyTypes?<div className="p-12 flex justify-center"><Loader2 className="w-6 h-6 animate-spin text-rose-500"/></div>:filtered.length===0?<div className="p-12 text-center text-sm font-bold text-slate-500">Nenhum tipo de imóvel encontrado</div>:<div className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.map((item,index)=><div key={item.id} draggable onDragStart={()=>setDragId(item.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>void drop(item)} className="p-4 flex items-center gap-2"><GripVertical className="w-4 h-4 text-slate-300 cursor-grab"/><div className="w-10 h-10 rounded-xl bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 flex items-center justify-center"><Building2 className="w-5 h-5"/></div><div className="flex-1 min-w-0"><p className="text-sm font-bold text-slate-900 dark:text-white">{item.name}</p><p className="text-[10px] text-slate-400 truncate">{item.description||'Sem descrição'}</p></div><div className="hidden sm:flex"><button disabled={index===0||busy!==null} onClick={()=>void move(item,-1)} className="p-1.5 text-slate-400 disabled:opacity-20" title="Mover para cima"><ArrowUp className="w-4 h-4"/></button><button disabled={index===filtered.length-1||busy!==null} onClick={()=>void move(item,1)} className="p-1.5 text-slate-400 disabled:opacity-20" title="Mover para baixo"><ArrowDown className="w-4 h-4"/></button></div><Switch checked={item.isActive} disabled={busy===item.id} onChange={()=>void toggle(item)} label={item.isActive?'Desativar tipo':'Ativar tipo'}/><button onClick={()=>startEdit(item)} className="p-2.5 rounded-xl bg-indigo-50 text-indigo-600"><Pencil className="w-4 h-4"/></button>{deleteId===item.id?<><button onClick={()=>void remove(item)} className="px-2 py-2 rounded-lg bg-rose-600 text-white text-[10px] font-bold">Confirmar</button><button onClick={()=>setDeleteId(null)} className="text-[10px]">Cancelar</button></>:<button onClick={()=>setDeleteId(item.id)} className="p-2.5 rounded-xl bg-rose-50 text-rose-600"><Trash2 className="w-4 h-4"/></button>}</div>)}</div>}
  </AdminCatalogSection>
  {modalOpen&&<div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-2xl p-6 space-y-5"><div><h3 className="text-xl font-black font-['Outfit']">{editing?'Editar tipo':'Novo tipo de imóvel'}</h3><p className="text-xs text-slate-500 mt-1">As alterações salvas serão atualizadas automaticamente no portal.</p></div><div className="grid sm:grid-cols-2 gap-4"><label className="sm:col-span-2 text-xs font-bold">Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} maxLength={100} className="mt-1.5 w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700"/></label><label className="sm:col-span-2 text-xs font-bold">Descrição<input value={form.description} maxLength={180} onChange={e=>setForm({...form,description:e.target.value})} className="mt-1.5 w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700"/></label><label className="sm:col-span-2 text-xs font-bold">Ícone<select value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})} className="mt-1.5 w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">{CATALOG_ICON_OPTIONS.slice(0,9).map(i=><option key={i.value} value={i.value}>{i.label}</option>)}</select></label></div><div className="flex justify-end gap-2"><button onClick={()=>setModalOpen(false)} className="px-5 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 text-xs font-bold">Cancelar</button><button disabled={busy!==null} onClick={()=>void save()} className="px-5 py-2.5 rounded-xl bg-rose-600 text-white text-xs font-bold flex items-center gap-2 disabled:opacity-50">{busy&&<Loader2 className="w-4 h-4 animate-spin"/>}Salvar alterações</button></div></div></div>}
  </>;
};
