import React, { useMemo, useState } from 'react';
import { Building2, Loader2, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { useApp, useCatalog } from '../../context/AppContext';
import { createPropertyType, deletePropertyType, PropertyTypeCatalogItem, PropertyTypeInput, setPropertyTypeActive, updatePropertyType } from '../../lib/propertyTypesCatalog';

const ICONS = ['Building','Building2','Home','Store','Maximize2','Trees','Tractor','Warehouse','Sparkles'];
const emptyForm: PropertyTypeInput = { name:'', description:'', icon:'Building2', displayOrder:10 };

export const AdminPropertyTypesPanel: React.FC = () => {
  const { addToast } = useApp();
  const { propertyTypes, loadingPropertyTypes, propertyTypesError, refreshPropertyTypes } = useCatalog();
  const [search,setSearch]=useState(''); const [editing,setEditing]=useState<PropertyTypeCatalogItem|null>(null);
  const [form,setForm]=useState<PropertyTypeInput>(emptyForm); const [open,setOpen]=useState(false);
  const [busy,setBusy]=useState<string|null>(null); const [deleteId,setDeleteId]=useState<string|null>(null);
  const filtered=useMemo(()=>propertyTypes.filter(item=>item.name.toLocaleLowerCase('pt-BR').includes(search.trim().toLocaleLowerCase('pt-BR'))),[propertyTypes,search]);
  const startNew=()=>{setEditing(null);setForm({...emptyForm,displayOrder:propertyTypes.reduce((n,i)=>Math.max(n,i.displayOrder),0)+10});setOpen(true);};
  const startEdit=(item:PropertyTypeCatalogItem)=>{setEditing(item);setForm({name:item.name,description:item.description,icon:item.icon,displayOrder:item.displayOrder});setOpen(true);};
  const save=async()=>{if(!form.name.trim())return addToast({type:'warning',title:'Nome obrigatório',message:'Informe o nome do tipo de imóvel.'});setBusy(editing?.id||'new');try{if(editing)await updatePropertyType(editing.id,form);else await createPropertyType(form);await refreshPropertyTypes();setOpen(false);addToast({type:'success',title:editing?'Tipo atualizado':'Tipo criado',message:'A alteração já está disponível no portal.'});}catch(error:any){addToast({type:'error',title:'Alteração não salva',message:error?.message||'Tente novamente.'});}finally{setBusy(null);}};
  const toggle=async(item:PropertyTypeCatalogItem)=>{setBusy(item.id);try{await setPropertyTypeActive(item.id,!item.isActive);await refreshPropertyTypes();}catch{addToast({type:'error',title:'Situação não alterada'});}finally{setBusy(null);}};
  const remove=async(item:PropertyTypeCatalogItem)=>{setBusy(item.id);try{await deletePropertyType(item.id);await refreshPropertyTypes();addToast({type:'success',title:'Tipo excluído'});}catch(error:any){addToast({type:'warning',title:'Exclusão não realizada',message:error?.message||'Desative o tipo para preservá-lo.'});}finally{setBusy(null);setDeleteId(null);}};
  return <section className="space-y-4">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="text-xl font-black text-slate-900 dark:text-white font-['Outfit']">Tipos de imóveis</h2><p className="text-xs text-slate-500">Controle as opções do cadastro, busca e navegação.</p></div><button onClick={startNew} className="px-4 py-2.5 rounded-xl bg-rose-600 text-white text-xs font-bold flex items-center justify-center gap-2"><Plus className="w-4 h-4"/>Novo tipo</button></div>
    {propertyTypesError&&<div className="p-4 rounded-2xl bg-amber-50 text-amber-800 text-xs flex justify-between gap-3"><span>{propertyTypesError}</span><button onClick={()=>void refreshPropertyTypes()} className="font-bold">Tentar novamente</button></div>}
    <div className="rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden"><div className="p-4 border-b border-slate-100 dark:border-slate-800"><label className="relative block"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar tipo de imóvel" className="w-full pl-10 pr-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs"/></label></div>
    {loadingPropertyTypes?<div className="p-12 flex justify-center"><Loader2 className="w-6 h-6 animate-spin text-rose-500"/></div>:filtered.length===0?<div className="p-12 text-center text-sm font-bold text-slate-500">Nenhum tipo de imóvel encontrado</div>:<div className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.map(item=><div key={item.id} className="p-4 flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 flex items-center justify-center"><Building2 className="w-5 h-5"/></div><div className="flex-1 min-w-0"><p className="text-sm font-bold text-slate-900 dark:text-white">{item.name}</p><p className="text-[10px] text-slate-400 truncate">{item.description||'Sem descrição'} · Ordem {item.displayOrder}</p></div><button role="switch" aria-checked={item.isActive} disabled={busy===item.id} onClick={()=>void toggle(item)} className={`relative w-11 h-6 rounded-full ${item.isActive?'bg-emerald-500':'bg-slate-300'}`}><span className={`absolute top-1 w-4 h-4 rounded-full bg-white shadow transition-transform ${item.isActive?'translate-x-1':'-translate-x-4'}`}/></button><button onClick={()=>startEdit(item)} className="p-2.5 rounded-xl bg-indigo-50 text-indigo-600"><Pencil className="w-4 h-4"/></button>{deleteId===item.id?<><button onClick={()=>void remove(item)} className="px-2 py-2 rounded-lg bg-rose-600 text-white text-[10px] font-bold">Confirmar</button><button onClick={()=>setDeleteId(null)} className="text-[10px]">Cancelar</button></>:<button onClick={()=>setDeleteId(item.id)} className="p-2.5 rounded-xl bg-rose-50 text-rose-600"><Trash2 className="w-4 h-4"/></button>}</div>)}</div>}</div>
    {open&&<div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-3xl bg-white dark:bg-slate-900 p-6 space-y-4"><div><h3 className="text-xl font-black">{editing?'Editar tipo':'Novo tipo de imóvel'}</h3><p className="text-xs text-slate-500">O identificador é criado automaticamente e permanece estável.</p></div><label className="text-xs font-bold block">Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1.5 w-full p-3 rounded-xl bg-slate-50 dark:bg-slate-800 border"/></label><label className="text-xs font-bold block">Descrição<input value={form.description} maxLength={180} onChange={e=>setForm({...form,description:e.target.value})} className="mt-1.5 w-full p-3 rounded-xl bg-slate-50 dark:bg-slate-800 border"/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">Ícone<select value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})} className="mt-1.5 w-full p-3 rounded-xl bg-slate-50 dark:bg-slate-800 border">{ICONS.map(i=><option key={i}>{i}</option>)}</select></label><label className="text-xs font-bold">Ordem<input type="number" min="0" value={form.displayOrder} onChange={e=>setForm({...form,displayOrder:Math.max(0,Number(e.target.value))})} className="mt-1.5 w-full p-3 rounded-xl bg-slate-50 dark:bg-slate-800 border"/></label></div><div className="flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="px-4 py-2.5 rounded-xl border text-xs font-bold">Cancelar</button><button disabled={busy!==null} onClick={()=>void save()} className="px-4 py-2.5 rounded-xl bg-rose-600 text-white text-xs font-bold">Salvar alterações</button></div></div></div>}
  </section>;
};
