import React, { useEffect, useRef, useState } from 'react';
import { Building2, ImagePlus, Loader2, RotateCcw, Save, Trash2 } from 'lucide-react';
import { useApp, useCatalog } from '../../context/AppContext';
import { deletePortalAsset, PortalAssetKind, uploadPortalAsset } from '../../lib/portalAssets';
import { DEFAULT_PORTAL_IDENTITY, PortalIdentitySettings, savePortalIdentity } from '../../lib/portalSettings';
import { AdminCatalogSection } from './AdminCatalogSection';

interface Props { open:boolean; onToggle:()=>void; }
const assets:{kind:PortalAssetKind;url:keyof PortalIdentitySettings;path:keyof PortalIdentitySettings;label:string;hint:string}[]=[
  {kind:'logo',url:'logoUrl',path:'logoPath',label:'Logotipo',hint:'Preferencialmente com fundo transparente'},
  {kind:'favicon',url:'faviconUrl',path:'faviconPath',label:'Ícone do navegador',hint:'Imagem quadrada'},
  {kind:'hero',url:'heroImageUrl',path:'heroImagePath',label:'Imagem principal',hint:'Formato horizontal e alta resolução'},
  {kind:'share',url:'shareImageUrl',path:'shareImagePath',label:'Imagem de compartilhamento',hint:'Recomendado: 1200 × 630 pixels'}
];

export const AdminPortalIdentityPanel:React.FC<Props>=({open,onToggle})=>{
  const {portalIdentity,refreshPortalIdentity}=useCatalog(); const {addToast}=useApp();
  const [form,setForm]=useState(portalIdentity); const [busy,setBusy]=useState<string|null>(null);
  const inputs=useRef<Record<string,HTMLInputElement|null>>({});
  useEffect(()=>setForm(portalIdentity),[portalIdentity]);
  const upload=async(kind:PortalAssetKind,file?:File)=>{if(!file)return;setBusy(kind);try{const slot=assets.find(item=>item.kind===kind)!;const uploaded=await uploadPortalAsset(kind,file);if(!uploaded)return;setForm(current=>({...current,[slot.url]:uploaded.url,[slot.path]:uploaded.path}));addToast({type:'success',title:'Imagem preparada',message:'Confira a prévia e clique em Salvar alterações.'});}catch(error:any){addToast({type:'error',title:'Imagem não enviada',message:error?.message||'Não foi possível processar a imagem.'});}finally{setBusy(null);}};
  const remove=(slot:typeof assets[number])=>setForm(current=>({...current,[slot.url]:'',[slot.path]:''}));
  const save=async()=>{if(!form.portalName.trim())return addToast({type:'warning',title:'Nome obrigatório',message:'Informe o nome do portal.'});setBusy('save');try{await savePortalIdentity(form);for(const slot of assets){const oldPath=String(portalIdentity[slot.path]||'');const newPath=String(form[slot.path]||'');if(oldPath&&oldPath!==newPath)await deletePortalAsset(oldPath);}await refreshPortalIdentity();addToast({type:'success',title:'Identidade atualizada',message:'A nova identidade já está disponível no portal.'});}catch(error:any){addToast({type:'error',title:'Alterações não salvas',message:error?.message||'Tente novamente.'});}finally{setBusy(null);}};
  const restore=()=>setForm(DEFAULT_PORTAL_IDENTITY);
  return <AdminCatalogSection title="Identidade do portal" description="Configure marca, cores e imagens institucionais." activeCount={1} inactiveCount={0} open={open} onToggle={onToggle} action={<button disabled={busy!==null} onClick={()=>void save()} className="px-4 py-2.5 rounded-xl bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold flex items-center gap-2 disabled:opacity-50">{busy==='save'?<Loader2 className="w-4 h-4 animate-spin"/>:<Save className="w-4 h-4"/>}Salvar alterações</button>}>
    <div className="p-4 sm:p-6 space-y-6">
      <div className="grid sm:grid-cols-2 gap-4"><label className="text-xs font-bold">Nome do portal<input value={form.portalName} maxLength={60} onChange={event=>setForm({...form,portalName:event.target.value})} className="mt-1.5 w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 font-normal"/></label><label className="text-xs font-bold">Subtítulo ou slogan<input value={form.slogan} maxLength={100} onChange={event=>setForm({...form,slogan:event.target.value})} className="mt-1.5 w-full px-4 py-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 font-normal"/></label></div>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{(['primaryColor','secondaryColor','accentColor'] as const).map((key,index)=><label key={key} className="text-xs font-bold">{['Cor principal','Cor secundária','Cor de destaque'][index]}<span className="mt-1.5 flex items-center gap-3 px-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700"><input type="color" value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})} className="w-9 h-9 rounded-lg border-0 bg-transparent"/><input value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})} pattern="^#[0-9A-Fa-f]{6}$" className="min-w-0 w-full bg-transparent font-mono font-normal"/></span></label>)}</div>
      <div className="grid sm:grid-cols-2 gap-4">{assets.map(slot=><div key={slot.kind} className="rounded-2xl border border-slate-200 dark:border-slate-700 p-4 space-y-3"><div><p className="text-sm font-bold">{slot.label}</p><p className="text-[11px] text-slate-500">{slot.hint}</p></div><div className="h-36 rounded-xl bg-slate-100 dark:bg-slate-800 overflow-hidden flex items-center justify-center">{form[slot.url]?<img src={String(form[slot.url])} alt={`Prévia de ${slot.label}`} className="w-full h-full object-contain"/>:<Building2 className="w-10 h-10 text-slate-300"/>}</div><input ref={element=>{inputs.current[slot.kind]=element;}} type="file" accept="image/jpeg,image/png,image/webp,image/avif,image/heic,image/heif" className="hidden" onChange={event=>{void upload(slot.kind,event.target.files?.[0]);event.target.value='';}}/><div className="flex gap-2"><button disabled={busy!==null} onClick={()=>inputs.current[slot.kind]?.click()} className="flex-1 px-3 py-2.5 rounded-xl bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 text-xs font-bold flex items-center justify-center gap-2">{busy===slot.kind?<Loader2 className="w-4 h-4 animate-spin"/>:<ImagePlus className="w-4 h-4"/>}{form[slot.url]?'Substituir':'Selecionar imagem'}</button>{form[slot.url]&&<button disabled={busy!==null} onClick={()=>void remove(slot)} title="Excluir imagem" className="p-2.5 rounded-xl bg-rose-50 text-rose-600"><Trash2 className="w-4 h-4"/></button>}</div></div>)}</div>
      <div className="rounded-2xl border border-slate-200 dark:border-slate-700 p-4" style={{borderColor:form.primaryColor}}><p className="text-[10px] font-bold uppercase text-slate-400 mb-3">Prévia</p><div className="flex items-center gap-3">{form.logoUrl?<img src={form.logoUrl} alt="" className="w-12 h-12 object-contain rounded-xl"/>:<div className="w-12 h-12 rounded-xl flex items-center justify-center text-white" style={{background:`linear-gradient(135deg,${form.accentColor},${form.primaryColor},${form.secondaryColor})`}}><Building2/></div>}<div><p className="text-xl font-black font-['Outfit']">{form.portalName||'Nome do portal'}</p><p className="text-xs text-slate-500">{form.slogan||'Subtítulo do portal'}</p></div></div></div>
      <button onClick={restore} className="text-xs font-bold text-slate-500 flex items-center gap-2"><RotateCcw className="w-4 h-4"/>Restaurar identidade padrão</button>
    </div>
  </AdminCatalogSection>;
};
