import React from 'react';
import { Building2, Phone, Mail, MapPin, Instagram, Facebook, Youtube, Linkedin, ShieldCheck } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { useCatalog } from '../../context/CatalogContext';

export const Footer: React.FC = () => {
  const { properties, setCurrentView, setFilters, openLegalPage } = useApp();
  const { activePropertyTypes, propertyTypesError, footerSettings, portalIdentity } = useCatalog();
  const availableCities = React.useMemo(() => Array.from(new Set(properties.map(item => item.city?.trim()).filter(Boolean) as string[])).sort(), [properties]);
  const availableNeighborhoods = React.useMemo(() => Array.from(new Set(properties.map(item => item.neighborhood?.trim()).filter(Boolean) as string[])).sort(), [properties]);
  const fallbackPropertyTypes = [{id:'apartment',label:'Apartamento'},{id:'house',label:'Casa de Bairro'},{id:'condo_house',label:'Casa em Condomínio'},{id:'land',label:'Terreno'},{id:'chacara',label:'Chácara'},{id:'farm',label:'Sítio/Fazenda'},{id:'commercial',label:'Comercial'},{id:'launch',label:'Lançamento'}];
  const propertyTypes = propertyTypesError ? fallbackPropertyTypes : activePropertyTypes.map(item => ({ id:item.id,label:item.name }));
  const openSearch = (searchTerm:string, city?:string) => { setFilters(current => ({...current,city:city||current.city,searchTerm})); setCurrentView('search'); window.scrollTo({top:0,behavior:'smooth'}); };
  const socials = [{url:footerSettings.instagramUrl,label:'Instagram',Icon:Instagram},{url:footerSettings.facebookUrl,label:'Facebook',Icon:Facebook},{url:footerSettings.youtubeUrl,label:'YouTube',Icon:Youtube},{url:footerSettings.linkedinUrl,label:'LinkedIn',Icon:Linkedin}];

  return <footer className="bg-slate-900 text-slate-300 pt-16 pb-12 border-t border-slate-800"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 pb-12 border-b border-slate-800">
      <div className="space-y-4"><div className="flex items-center gap-3">{portalIdentity.logoUrl?<img src={portalIdentity.logoUrl} alt="" className="w-10 h-10 rounded-xl object-contain"/>:<div className="w-10 h-10 rounded-xl flex items-center justify-center text-white shadow-lg" style={{background:`linear-gradient(135deg,${portalIdentity.accentColor},${portalIdentity.primaryColor},${portalIdentity.secondaryColor})`}}><Building2 className="w-6 h-6"/></div>}<span className="font-extrabold text-2xl text-white font-['Outfit']">{portalIdentity.portalName}</span></div><p className="text-sm text-slate-400 leading-relaxed">{footerSettings.brandDescription}</p><div className="space-y-1 text-xs text-slate-400"><div className="flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0"/><span>{footerSettings.creci}</span></div><div className="pl-6">{footerSettings.professionalName}</div></div></div>
      <div className="space-y-3"><h4 className="text-sm font-bold uppercase tracking-wider text-white">{footerSettings.serviceTitle}</h4><ul className="space-y-2.5 text-sm"><li className="flex items-center gap-2.5 text-slate-400"><Phone className="w-4 h-4 text-rose-500"/><span>{footerSettings.phone}</span></li><li className="flex items-center gap-2.5 text-slate-400"><Mail className="w-4 h-4 text-rose-500"/><span>{footerSettings.email}</span></li><li className="flex items-start gap-2.5 text-slate-400"><MapPin className="w-4 h-4 text-rose-500 shrink-0 mt-1"/><span>{footerSettings.address}</span></li></ul><p className="text-xs text-slate-500 pt-2">{footerSettings.businessHours}</p></div>
      <div className="space-y-3"><h4 className="text-sm font-bold uppercase tracking-wider text-white">{footerSettings.navigationTitle}</h4><ul className="space-y-2 text-sm">{propertyTypes.map(type=><li key={type.id}><button onClick={()=>{setFilters(current=>({...current,types:[type.id as any],purpose:'all',searchTerm:''}));setCurrentView('search');window.scrollTo({top:0,behavior:'smooth'});}} className="hover:text-rose-400 transition-colors text-left">{type.label}</button></li>)}</ul></div>
      <div className="space-y-3"><h4 className="text-sm font-bold uppercase tracking-wider text-white">{footerSettings.connectionTitle}</h4><p className="text-xs text-slate-400">{footerSettings.newsletterText}</p><div className="flex gap-2"><input type="email" placeholder="Seu e-mail" className="w-full px-3 py-2 text-xs rounded-lg bg-slate-800 border border-slate-700 text-white placeholder-slate-500 focus:outline-none focus:border-rose-500"/><button className="px-3 py-2 bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold rounded-lg">Enviar</button></div><div className="flex gap-3 pt-2">{socials.filter(item=>/^https?:\/\//i.test(item.url)).map(({url,label,Icon})=><a key={label} href={url} target="_blank" rel="noreferrer" aria-label={label} className="p-2 rounded-lg bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700 transition-colors"><Icon className="w-4 h-4"/></a>)}</div></div>
    </div>
    <div className="py-8 border-b border-slate-800 grid grid-cols-1 md:grid-cols-2 gap-8 text-xs text-slate-400"><div><h5 className="font-semibold text-slate-200 mb-2.5">Bairros com imóveis disponíveis:</h5><div className="flex flex-wrap gap-2">{availableNeighborhoods.length?availableNeighborhoods.map(item=><button key={item} onClick={()=>openSearch(item)} className="px-2.5 py-1 rounded bg-slate-800/80 hover:bg-slate-700 hover:text-white">{item}</button>):<span className="text-slate-500 italic">Nenhum bairro cadastrado no momento</span>}</div></div><div><h5 className="font-semibold text-slate-200 mb-2.5">Cidades com imóveis disponíveis:</h5><div className="flex flex-wrap gap-2">{availableCities.length?availableCities.map(item=><button key={item} onClick={()=>openSearch(item,item)} className="px-2.5 py-1 rounded bg-slate-800/80 hover:bg-slate-700 hover:text-white">{item}</button>):<span className="text-slate-500 italic">Nenhuma cidade cadastrada no momento</span>}</div></div></div>
    <div className="pt-6 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-500 gap-4"><p>{footerSettings.copyrightText}</p><div className="flex flex-wrap items-center justify-center sm:justify-end gap-x-5 gap-y-2"><button onClick={()=>openLegalPage('terms')} className="hover:text-slate-300">Termos de Uso</button><button onClick={()=>openLegalPage('privacy')} className="hover:text-slate-300">Política de Privacidade (LGPD)</button><button onClick={()=>openLegalPage('consumer')} className="hover:text-slate-300">Código de Defesa do Consumidor</button><button onClick={()=>openLegalPage('cookies')} className="hover:text-slate-300">Preferências de Cookies</button></div></div>
  </div></footer>;
};
