import { Property } from '../../types';
import { BROKERS } from './mockUsers';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    code: '24636068-MEOA',
    userId: 'user_current',
    advertiser: BROKERS[2],
    title: 'Central Station - Apartamento Alto Padrão no Centro',
    slug: 'central-station-apartamento-sorocaba-centro-24636068',
    description: 'No coração vibrante de Sorocaba, nasce um novo ícone urbano: Central Station. Um empreendimento que une mobilidade, conveniência e valorização em um só endereço. Apartamento finamente decorado com acabamentos nobres, varanda gourmet integrada à sala e cozinha americana.',
    purpose: 'sale',
    type: 'apartment',
    status: 'active',
    featured: true,
    isExclusive: true,
    price: 485000,
    pricePerMeter: 9700,
    condoFee: 420,
    iptuFee: 110,
    totalArea: 68,
    usefulArea: 50,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 1,
    floor: 12,
    totalFloors: 24,
    solarOrientation: 'Manhã',
    constructionYear: 2024,
    addressStreet: 'Rua da Penha',
    addressNumber: '1320',
    neighborhood: 'Centro',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18010-002',
    latitude: -23.5015,
    longitude: -47.4580,
    amenities: ['piscina', 'academia', 'varanda_gourmet', 'portaria_24h', 'elevador', 'ar_condicionado', 'aquecimento_gas'],
    media: [
      {
        id: 'm1',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Living integrado com iluminação em LED',
        category: 'sala',
        isCover: true,
        order: 1
      },
      {
        id: 'm2',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Sala de jantar e bancada contemporânea',
        category: 'sala',
        isCover: false,
        order: 2
      },
      {
        id: 'm3',
        url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Suíte master com cabeceira ripada e painéis em marcenaria',
        category: 'quarto',
        isCover: false,
        order: 3
      },
      {
        id: 'm4',
        url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Banheiro com bancada em mármore esculpido',
        category: 'banheiro',
        isCover: false,
        order: 4
      }
    ],
    viewsCount: 3840,
    leadsCount: 42,
    favoritesCount: 156,
    sharesCount: 28,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-30T14:20:00Z'
  },
  {
    id: 'prop-2',
    code: '38914022-ALPH',
    userId: 'user_current',
    advertiser: BROKERS[2],
    title: 'Mansão Neoclássica com Vista Panorâmica em Alphaville',
    slug: 'mansao-neoclassica-alphaville-nova-esplanada-38914022',
    description: 'Espetacular residência em condomínio fechado com arquitetura contemporânea e acabamentos importados. Pé direito duplo de 7 metros, automação residencial completa, adega climatizada, elevador privativo e piscina com borda infinita aquecida.',
    purpose: 'sale',
    type: 'condo_house',
    status: 'active',
    featured: true,
    isExclusive: true,
    price: 3750000,
    pricePerMeter: 8333,
    condoFee: 1100,
    iptuFee: 480,
    totalArea: 650,
    usefulArea: 450,
    bedrooms: 4,
    suites: 4,
    bathrooms: 6,
    parkingSpots: 6,
    floor: 2,
    totalFloors: 2,
    solarOrientation: 'Norte',
    constructionYear: 2025,
    addressStreet: 'Alameda dos Ipês',
    neighborhood: 'Alphaville Nova Esplanada',
    city: 'Votorantim',
    state: 'SP',
    zipCode: '18118-000',
    latitude: -23.5510,
    longitude: -47.4720,
    amenities: ['piscina', 'churrasqueira', 'academia', 'quadra_tenis', 'sauna', 'portaria_24h', 'varanda_gourmet', 'energia_solar', 'carregador_eletrico'],
    media: [
      {
        id: 'm201',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Fachada imponente com iluminação cênica noturna',
        category: 'fachada',
        isCover: true,
        order: 1
      },
      {
        id: 'm202',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Área de lazer com piscina de borda infinita e deck de madeira',
        category: 'lazer',
        isCover: false,
        order: 2
      },
      {
        id: 'm203',
        url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Living com pé direito duplo e lareira a gás',
        category: 'sala',
        isCover: false,
        order: 3
      }
    ],
    viewsCount: 5120,
    leadsCount: 31,
    favoritesCount: 284,
    sharesCount: 65,
    createdAt: '2026-08-01T12:00:00Z',
    updatedAt: '2026-08-28T09:15:00Z'
  },
  {
    id: 'prop-3',
    code: '19854091-CAMP',
    userId: 'user_1',
    advertiser: BROKERS[0],
    title: 'Apartamento Garden no Parque Campolim com 3 Suítes',
    slug: 'apartamento-garden-parque-campolim-sorocaba-19854091',
    description: 'Privilégio de morar em uma casa com a segurança de um condomínio vertical. Área externa privativa de 65m² com jacuzzi aquecida e espaço gourmet exclusivo.',
    purpose: 'sale',
    type: 'apartment',
    status: 'active',
    featured: true,
    price: 1350000,
    pricePerMeter: 8437,
    condoFee: 890,
    iptuFee: 240,
    totalArea: 210,
    usefulArea: 160,
    bedrooms: 3,
    suites: 3,
    bathrooms: 4,
    parkingSpots: 3,
    floor: 1,
    totalFloors: 18,
    solarOrientation: 'Manhã',
    constructionYear: 2023,
    addressStreet: 'Avenida Professora Izoraida Marques Peres',
    neighborhood: 'Parque Campolim',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18048-110',
    latitude: -23.5280,
    longitude: -47.4650,
    amenities: ['piscina', 'churrasqueira', 'academia', 'playground', 'salao_festas', 'portaria_24h', 'pet_place', 'moveis_planejados'],
    media: [
      {
        id: 'm301',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Garden privativo com pergolado e spa',
        category: 'lazer',
        isCover: true,
        order: 1
      },
      {
        id: 'm302',
        url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Cozinha planejada com ilha central e eletros embutidos',
        category: 'cozinha',
        isCover: false,
        order: 2
      }
    ],
    viewsCount: 2790,
    leadsCount: 19,
    favoritesCount: 98,
    sharesCount: 14,
    createdAt: '2026-08-15T15:30:00Z',
    updatedAt: '2026-08-29T18:00:00Z'
  },
  {
    id: 'prop-4',
    code: '74125896-ALUG',
    userId: 'user_1',
    advertiser: BROKERS[0],
    title: 'Casa Térrea Mobiliada para Locação no Condomínio Giverny',
    slug: 'casa-terrea-condominio-giverny-locacao-74125896',
    description: 'Casa totalmente térrea, mobiliada e decorada com projeto assinado por arquiteto renomado. 3 suítes completas, piscina aquecida com hidro, energia solar e ar-condicionado em todos os cômodos.',
    purpose: 'rent',
    type: 'condo_house',
    status: 'active',
    featured: false,
    price: 14000,
    condoFee: 750,
    iptuFee: 320,
    totalArea: 380,
    usefulArea: 240,
    bedrooms: 3,
    suites: 3,
    bathrooms: 4,
    parkingSpots: 4,
    solarOrientation: 'Tarde',
    constructionYear: 2022,
    addressStreet: 'Rua Claude Monet',
    neighborhood: 'Giverny',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18048-000',
    latitude: -23.5410,
    longitude: -47.4690,
    amenities: ['piscina', 'churrasqueira', 'quadra_tenis', 'portaria_24h', 'ar_condicionado', 'energia_solar', 'moveis_planejados'],
    media: [
      {
        id: 'm401',
        url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Fachada frontal moderna com paisagismo tropical',
        category: 'fachada',
        isCover: true,
        order: 1
      },
      {
        id: 'm402',
        url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Suíte master com closet e vista para o jardim privativo',
        category: 'quarto',
        isCover: false,
        order: 2
      }
    ],
    viewsCount: 1650,
    leadsCount: 14,
    favoritesCount: 72,
    sharesCount: 11,
    createdAt: '2026-08-18T08:00:00Z',
    updatedAt: '2026-08-30T11:00:00Z'
  },
  {
    id: 'prop-5',
    code: '9595997-MEOA',
    userId: 'user_2',
    advertiser: BROKERS[1],
    title: 'Arbo Paulistano - Apartamentos de 80 a 115m² em Construção',
    slug: 'arbo-paulistano-apartamentos-sorocaba-9595997',
    description: 'Breve lançamento no ponto mais nobre da Zona Sul. Torre única com lazer estilo resort, piscina climatizada com raia de 25m, pista de caminhada privativa, coworking e bicicletário compartilhado.',
    purpose: 'launch',
    type: 'apartment',
    status: 'active',
    featured: true,
    price: 790000,
    pricePerMeter: 9875,
    condoFee: 550,
    iptuFee: 180,
    totalArea: 115,
    usefulArea: 80,
    bedrooms: 3,
    suites: 2,
    bathrooms: 3,
    parkingSpots: 2,
    deliveryDate: '2027-12-01',
    addressStreet: 'Rua Senador Vergueiro',
    neighborhood: 'Jardim Paulistano',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18040-000',
    latitude: -23.5150,
    longitude: -47.4520,
    amenities: ['piscina', 'churrasqueira', 'academia', 'cinema', 'sauna', 'portaria_24h', 'carregador_eletrico', 'pet_place'],
    media: [
      {
        id: 'm501',
        url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Perspectiva artística da fachada do Arbo Paulistano',
        category: 'fachada',
        isCover: true,
        order: 1
      },
      {
        id: 'm502',
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Complexo aquático com bangalôs e deck molhado',
        category: 'lazer',
        isCover: false,
        order: 2
      }
    ],
    viewsCount: 6200,
    leadsCount: 88,
    favoritesCount: 310,
    sharesCount: 94,
    createdAt: '2026-07-25T11:00:00Z',
    updatedAt: '2026-08-30T17:45:00Z'
  },
  {
    id: 'prop-6',
    code: '45812390-ALUG',
    userId: 'user_current',
    advertiser: BROKERS[2],
    title: 'Studio Mobiliado & Equipado no Além Ponte - Ideal p/ Investidores',
    slug: 'studio-mobiliado-alem-ponte-sorocaba-45812390',
    description: 'Studio pronto para morar ou rentabilizar em Airbnb com retorno estimado de 0.8% ao mês. Mobília planejada completa, eletrodomésticos inverter, fechadura digital biométrica e vaga de garagem coberta.',
    purpose: 'rent',
    type: 'apartment',
    status: 'active',
    featured: false,
    price: 2400,
    condoFee: 320,
    iptuFee: 65,
    totalArea: 42,
    usefulArea: 36,
    bedrooms: 1,
    suites: 1,
    bathrooms: 1,
    parkingSpots: 1,
    floor: 7,
    totalFloors: 14,
    solarOrientation: 'Manhã',
    constructionYear: 2024,
    addressStreet: 'Rua Coronel Nogueira Padilha',
    neighborhood: 'Além Ponte',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18020-000',
    latitude: -23.5080,
    longitude: -47.4430,
    amenities: ['academia', 'cinema', 'portaria_24h', 'elevador', 'ar_condicionado', 'moveis_planejados'],
    media: [
      {
        id: 'm601',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Studio com divisória ripada entre quarto e estar',
        category: 'sala',
        isCover: true,
        order: 1
      }
    ],
    viewsCount: 1420,
    leadsCount: 18,
    favoritesCount: 65,
    sharesCount: 9,
    createdAt: '2026-08-20T14:00:00Z',
    updatedAt: '2026-08-30T16:00:00Z'
  },
  {
    id: 'prop-7',
    code: '88210344-IBITI',
    userId: 'user_2',
    advertiser: BROKERS[1],
    title: 'Casa Térrea Moderna com Piscina no Condomínio Ibiti Reserva',
    slug: 'casa-terrea-ibiti-reserva-sorocaba-88210344',
    description: 'Projeto moderno e clean no cobiçado Ibiti Reserva. 3 suítes sendo 1 master com hidromassagem e closet espaçoso. Cozinha integrada à área gourmet e piscina com cascata.',
    purpose: 'sale',
    type: 'condo_house',
    status: 'active',
    featured: false,
    price: 1180000,
    pricePerMeter: 5900,
    condoFee: 410,
    iptuFee: 160,
    totalArea: 300,
    usefulArea: 200,
    bedrooms: 3,
    suites: 3,
    bathrooms: 4,
    parkingSpots: 4,
    solarOrientation: 'Manhã',
    constructionYear: 2024,
    addressStreet: 'Alameda dos Jacarandás',
    neighborhood: 'Ibiti Reserva',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18087-000',
    latitude: -23.4680,
    longitude: -47.4320,
    amenities: ['piscina', 'churrasqueira', 'quadra_tenis', 'playground', 'portaria_24h', 'energia_solar'],
    media: [
      {
        id: 'm701',
        url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Fachada moderna em tons de concreto e madeira ripada',
        category: 'fachada',
        isCover: true,
        order: 1
      }
    ],
    viewsCount: 2310,
    leadsCount: 22,
    favoritesCount: 88,
    sharesCount: 19,
    createdAt: '2026-08-12T16:00:00Z',
    updatedAt: '2026-08-29T10:30:00Z'
  },
  {
    id: 'prop-8',
    code: '33491022-SANTA',
    userId: 'user_current',
    advertiser: BROKERS[2],
    title: 'Apartamento com Varanda Gourmet no Jardim Santa Rosália',
    slug: 'apartamento-jardim-santa-rosalia-sorocaba-33491022',
    description: 'Excelente localização próximo às principais avenidas e hipermercados. 3 dormitórios, varanda com churrasqueira a carvão e 2 vagas cobertas demarcadas.',
    purpose: 'sale',
    type: 'apartment',
    status: 'paused',
    featured: false,
    price: 620000,
    pricePerMeter: 6888,
    condoFee: 490,
    iptuFee: 130,
    totalArea: 110,
    usefulArea: 90,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 2,
    floor: 6,
    totalFloors: 16,
    solarOrientation: 'Manhã',
    constructionYear: 2021,
    addressStreet: 'Rua Nicolau Pereira Campos Vergueiro',
    neighborhood: 'Jardim Santa Rosália',
    city: 'Sorocaba',
    state: 'SP',
    zipCode: '18095-000',
    latitude: -23.4920,
    longitude: -47.4470,
    amenities: ['piscina', 'churrasqueira', 'academia', 'salao_festas', 'portaria_24h', 'elevador'],
    media: [
      {
        id: 'm801',
        url: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=400&q=80',
        mediaType: 'image',
        caption: 'Varanda gourmet com fechamento em vidro retrátil',
        category: 'sala',
        isCover: true,
        order: 1
      }
    ],
    viewsCount: 890,
    leadsCount: 6,
    favoritesCount: 34,
    sharesCount: 4,
    createdAt: '2026-08-05T10:00:00Z',
    updatedAt: '2026-08-25T12:00:00Z'
  }
];
